---
name: Build Hugo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: prepare
        uses: peaceiris/actions-hugo@v2
        with:
          version: '0.91.2'
          extended: true
      - name: build
        run: hugo --minify
