---
name: Build Hugo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: prepare
        uses: peaceiris/actions-hugo@v2
        with:
          version: '0.121.1'
          extended: true
      - name: build
        run: hugo --minify
      - name: cname
        run: |
          echo "www.wiramsee.de" > public/CNAME
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false
